// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
namespace InfiniBlazor.AutoDocumentation.RequiredSources;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class SourceCodes {
    public const string AutoDocumentAttributeTypeName = "InfiniBlazor.AutoDocumentation.AutoDocumentAttribute";
    public const string AutoDocumentAttributeSource = """
    // <auto-generated />
    using Microsoft.CodeAnalysis;
    namespace InfiniBlazor.AutoDocumentation;
    
    [System.AttributeUsage(
        System.AttributeTargets.Class
        | System.AttributeTargets.Struct
        | System.AttributeTargets.Property 
        | System.AttributeTargets.Method 
        | System.AttributeTargets.Field)]
    internal class AutoDocumentAttribute(string id) : System.Attribute {
        public string Id { get; } = id;
    }
    """;
}
