// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.GeneratorTools;
using Microsoft.CodeAnalysis;
using System.Buffers;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;

namespace InfiniLore.InfiniBlazor.SourceGenerators.Theming;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class ThemeSymbolsDtoWriter {
    private static string ToCssVariable(string input) {
        ReadOnlySpan<char> inputSpan = input.AsSpan();
        int[] tempArray = ArrayPool<int>.Shared.Rent(inputSpan.Length);
        char[] result = ArrayPool<char>.Shared.Rent(inputSpan.Length + inputSpan.Length + 1); 
    
        try {
            int index = 0;
            int count = 0;

            for (int i = 1; i < inputSpan.Length; i++) {
                bool currentIsDigit = char.IsDigit(inputSpan[i]);
                bool previousIsDigit = char.IsDigit(inputSpan[i - 1]);
            
                if (!(char.IsUpper(inputSpan[i]) || currentIsDigit && !previousIsDigit)) continue;

                tempArray[count * 2] = index;
                tempArray[count * 2 + 1] = i - index;
                count++;
                index = i;
            }

            if (index < inputSpan.Length) {
                tempArray[count * 2] = index;
                tempArray[count * 2 + 1] = inputSpan.Length - index;
                count++;
            }

            result[0] = '-';// First '-'
            result[1] = '-';// Second '-'
            int writePos = 2;// Start after '--'

            for (int i = 0; i < count; i++) {
                if (i > 0)
                    result[writePos++] = '-';

                int start = tempArray[i * 2];
                int length = tempArray[i * 2 + 1];

                for (int j = 0; j < length; j++) {
                    result[writePos++] = char.ToLower(inputSpan[start + j]);
                }
            }

            return new string(result, 0, writePos);
        }
        finally {
            ArrayPool<int>.Shared.Return(tempArray);
            ArrayPool<char>.Shared.Return(result);
        }
    }
    
    [SuppressMessage("ReSharper", "HeapView.CanAvoidClosure")]
    public static void WritePartialClass(ThemeSymbolsDto dto, GeneratorStringBuilder builder, Compilation compilation) {
        ImmutableArray<IPropertySymbol> cssData = dto.GetCssDataProperties(compilation);
            
        builder.AppendAutoGenerated()
            .AppendUsings("System.Collections.Frozen")
            .AppendNamespace(dto.NameSpace)
            .AppendLine()
            .AppendLine($"{dto.Accessibility} partial {dto.TypeKeyword} {dto.ClassName} {{")
            .Indent(
                static (b, args) => {
                    b.AppendLine("#region RgbValues");
                    
                    IEnumerable<IPropertySymbol> rgbProperties = args.themeProperties
                        .Where(property => property.HasAttributeWithDisplayName(TypeNames.InterpretAsRgbAttribute) );

                    b.ForEachAppendLine(rgbProperties, symbol => {
                        string name = symbol.Name;
                        string propertyName = name.ToLowerInvariant().EndsWith("rgb")
                            ? name.Substring(0, name.Length - 3)
                            : name;
                        
                        string converterCall = $"StringColorExtensions.ConvertToRgbValues({propertyName})";
                        return $"public string {name} => {converterCall};";
                    });
                    b.AppendLine("#endregion");
                    
                    b.AppendLine();
                    
                    b.AppendLine("#region CssVarValues");

                    // ReSharper disable once SuggestVarOrType_Elsewhere
                    var varProperties = args.themeProperties
                        .Where(property => property.HasAttributeWithDisplayName(TypeNames.InterpretAsVarAttribute))
                        .Select(property => (
                            property.Name,
                            VarName : property.GetAttributeWithDisplayName(TypeNames.InterpretAsVarAttribute)?.ConstructorArguments[0].Value as string,
                            HasInit : property.SetMethod is not null
                        ));
                    
                    
                    b.ForEach(varProperties, (builder, box) => {
                        string name = box.Name;
                        string? varName = box.VarName;

                        string propertyName = varName ?? (name.ToLowerInvariant().EndsWith("var")
                            ? name.Substring(0, name.Length - 3)
                            : name
                        );
                        string converterCall = $"$\"var({ToCssVariable(propertyName)})\"";

                        if (box.HasInit) {
                            builder.AppendLineIndented($"private string _cache{box.Name} = {converterCall};");
                            builder.AppendLineIndented($"public partial string {name} {{ get => _cache{box.Name}; init => _cache{box.Name} = value; }}");
                            return;
                        }
                        
                        builder.AppendLineIndented($"public partial string {name} => {converterCall};");
                    });
                    
                    
                    b.AppendLine("#endregion");
                },
                (dto, themeProperties: cssData)
            )
            .AppendLine()
            .Indent(
                static (b, args) => {
                    b.AppendLine("#region AsCssVariables");
                    
                    b.AppendLine("public IEnumerable<(string, string)> AsCssVariables() {");

                    // ReSharper disable once HeapView.CanAvoidClosure
                    b.ForEachAppendLineIndented(args.themeProperties, symbol => {
                        string cssVariableName = !args.dto.GenerateVariableStorage 
                            ? ToCssVariable(symbol.Name).ToQuotedString()
                            : $"{args.dto.ClassName}VariableNames.{symbol.Name}";
    
                        string property = symbol.Name;

                        return $"if (!string.IsNullOrEmpty({property})) yield return ({cssVariableName}, {property});";
                    });

                    b.AppendLine("}");
                    
                    b.AppendLine("#endregion");
                },
                (dto, themeProperties: cssData)
            )
            .AppendLine("}"); 
    }

    public static void WriteVariableNames(ThemeSymbolsDto dto, GeneratorStringBuilder builder, Compilation compilation) {
        ImmutableArray<IPropertySymbol> themeProperties = dto.GetCssDataProperties(compilation);
        
        builder.AppendAutoGenerated()
            .AppendUsings("System.Collections.Frozen")
            .AppendNamespace(dto.NameSpace)
            .AppendLine()
            .AppendLine($"public static class {dto.ClassName}VariableNames {{");

        builder.ForEachAppendLineIndented(themeProperties, symbol => {
            string cssVariableName = ToCssVariable(symbol.Name);
            return $"public const string {symbol.Name} = {cssVariableName.ToQuotedString()};";
        });
        
        builder.Append("}");
    }
}
