// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.GeneratorTools;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace InfiniLore.InfiniBlazor.Extensions.AutoDocumentation.SourceGenerators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class AutoDocumenterDataWriter {
    public const string FileName = "AutoDocumentorData.g.cs";
    private const string Namespace = "InfiniLore.InfiniBlazor.AutoDocumentation";

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    public static string GenerateFile(IEnumerable<AutoDocumentedData> data, string assemblyName, bool enableKrStyle, string propertyName) {
        GeneratorStringBuilder builder = new GeneratorStringBuilder()
            .AppendAutoGenerated()
            .AppendUsings(
                "System",
                "System.Collections.Frozen",
                "System.Collections.Immutable"
            )
            .AppendNamespace(Namespace)
            .AppendLine($"public partial class AutoDocumenterData_{assemblyName.Replace(".", "")} : {Namespace}.IAutoDocumenterData {{")
            .Indent(indentedAction: static (builder, box)
                    => WriteFileDataDictionary(builder, box.data.GroupBy(data => data.Id), box.enableKrStyle, box.propertyName),
                (data, enableKrStyle, propertyName)
            )
            .AppendLine("}");

        return builder.ToStringAndClear();
    }


    private static void WriteFileDataDictionary(GeneratorStringBuilder builder, IEnumerable<IGrouping<string, AutoDocumentedData>> dataArray, bool enableKrStyle, string propertyName) {
        builder.AppendLine($"public Lazy<FrozenDictionary<string, ImmutableArray<string>>> {propertyName} {{ get; }} = new Lazy<FrozenDictionary<string, ImmutableArray<string>>>(static () => new Dictionary<string, ImmutableArray<string>>() {{");

        foreach (IGrouping<string, AutoDocumentedData> grouping in dataArray) {
            builder.Indent(b => {
                b.AppendLine($"[\"{grouping.Key}\"] = [");

                foreach (AutoDocumentedData data in grouping) {
                    b.Builder.AppendLine("\"\"\"\"\"\"");

                    string body = data.Body;
                    if (enableKrStyle) {
                        body = EnforceKrStyle(data.Body);
                    }

                    foreach (string s in body.Split('\n')) {
                        b.Builder.AppendLine(s);
                    }
                    b.Builder.AppendLine("\"\"\"\"\"\",");
                }

                b.AppendLine("],");
            });
        }

        builder.AppendLine("}.ToFrozenDictionary());");
    }
    
    private static readonly Regex OpenBraceRegex = new(
        @"(\b(class|struct|interface|enum|method|if|else|while|for|do|switch|try|catch)([^{]*))\n\s*\{",
        RegexOptions.Singleline | RegexOptions.Compiled
    );

    private static readonly Regex CloseBraceRegex = new(
        @"\n\s*}",
        RegexOptions.Compiled
    );

    private static string EnforceKrStyle(string code) {
        // Use precompiled regex patterns for better performance
        code = OpenBraceRegex.Replace(
            code,
            "$1 {"
        );

        code = CloseBraceRegex.Replace(
            code,
            "\n}"
        );

        // Trim any leftover unnecessary spaces
        return code.Trim();
    }




}
