// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.GeneratorTools;
using System.Text.RegularExpressions;

namespace InfiniBlazor.AutoDocumentation;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class AutoDocumenterDataWriter {
    public const string FileName = "AutoDocumentorData.g.cs";
    private const string Namespace = "InfiniBlazor.AutoDocumentation";

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    public static string GenerateFile(IEnumerable<AutoDocumentedData> data, string assemblyName, bool enableKrStyle, string propertyName) {
        GeneratorStringBuilder builder = new GeneratorStringBuilder()
            .AppendAutoGenerated()
            .AppendUsings(
                "System",
                "System.Collections.Frozen",
                "System.Collections.Immutable"
            )
            .AppendNamespace(Namespace)
            .AppendLine($"public partial class AutoDocumenterData_{assemblyName.Replace(".", "")} : {Namespace}.IAutoDocumenterData {{")
            .Indent(indentedAction: static (builder, box)
                    => WriteFileDataDictionary(builder, box.data.GroupBy(data => data.Id), box.enableKrStyle, box.propertyName),
                (data, enableKrStyle, propertyName)
            )
            .AppendLine("}");

        return builder.ToStringAndClear();
    }


    private static void WriteFileDataDictionary(
        GeneratorStringBuilder builder,
        IEnumerable<IGrouping<string, AutoDocumentedData>> dataArray,
        bool enableKrStyle,
        string propertyName) {
    
        builder.AppendLine($"public Lazy<FrozenDictionary<string, ImmutableArray<string>>> {propertyName} {{ get; }} = new Lazy<FrozenDictionary<string, ImmutableArray<string>>>(static () => new Dictionary<string, ImmutableArray<string>>() {{");

        foreach (IGrouping<string, AutoDocumentedData>? grouping in dataArray) {
            builder.Indent(b => {
                b.AppendLine($"[\"{grouping.Key}\"] = [");

                foreach (AutoDocumentedData? data in grouping) {
                    string body = enableKrStyle ? EnforceKrStyle(data.Body) : data.Body;

                    b.Builder.AppendLine("\"\"\"\"\"\""); 
                    foreach (string line in body.Replace("\r", "").Split('\n')) {
                        b.Builder.AppendLine(line);
                    }
                    b.Builder.AppendLine("\"\"\"\"\"\","); 
                }

                b.AppendLine("],");
            });
        }

        builder.AppendLine("}.ToFrozenDictionary());");
    }


    private static readonly Regex OpenBraceRegex = new(
        @"(\b(class|struct|interface|enum|method|if|else|while|for|do|switch|try|catch)[^{]*?)\s*\r?\n\s*\{",
        RegexOptions.Singleline | RegexOptions.Compiled
    );

    private static readonly Regex CloseBraceRegex = new(
        @"\r?\n\s*\}",
        RegexOptions.Compiled
    );

    private static string EnforceKrStyle(string code) {
        code = OpenBraceRegex.Replace(code, "$1 {\n");
        code = CloseBraceRegex.Replace(code, "\n}");
        return code.TrimEnd();
    }
}
