// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using CodeOfChaos.GeneratorTools;
using System.Collections.Generic;

namespace InfiniLore.InfiniBlazor.Theming.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[Generator(LanguageNames.CSharp)]
public class ThemeSymbolsGenerator : IIncrementalGenerator {
    private const string GenerateThemeSymbolsAttributeFullName = "InfiniLore.InfiniBlazor.Theming.GenerateThemeSymbols";
    private const string IncludeAsCssVariableAttributeFullName = "InfiniLore.InfiniBlazor.Theming.IncludeAsCssVariable";
    private const string IThemeInterfaceFullName = "InfiniLore.InfiniBlazor.Theming.ITheme";

    private static ImmutableArray<IPropertySymbol>? IThemeProperties { get; set; }

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValueProvider<ImmutableArray<ThemeSymbolsDto>> data = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(dto => dto is not null)
            .Collect()!;

        context.RegisterSourceOutput(context.CompilationProvider.Combine(data), GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken ct) {
        // Check if it's a class declaration
        if (node is not ClassDeclarationSyntax classDeclaration)
            return false;

        // Check if it has any attributes
        return classDeclaration.AttributeLists.Count > 0;
    }

    private static ThemeSymbolsDto? Transform(GeneratorSyntaxContext context, CancellationToken ct) {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        SemanticModel semanticModel = context.SemanticModel;

        // Get the symbol for the class
        if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol) return null;

        // Check if it has the GenerateThemeSymbols attribute
        bool hasGenerateThemeSymbolsAttribute = classSymbol.GetAttributes()
            .Any(static attr => attr.AttributeClass?.ToDisplayString() == GenerateThemeSymbolsAttributeFullName);
        if (!hasGenerateThemeSymbolsAttribute) return null;

        // Check if it implements ITheme
        bool implementsITheme = classSymbol.AllInterfaces
            .Any(static i => i.ToDisplayString() == IThemeInterfaceFullName);

        return implementsITheme
            ? new ThemeSymbolsDto(classSymbol)
            : null;
    }

    private static void GenerateSources(SourceProductionContext context, (Compilation Compilation, ImmutableArray<ThemeSymbolsDto> Data) tuple) {
        (Compilation compilation, ImmutableArray<ThemeSymbolsDto> data) = tuple;
        
        var builder = new GeneratorStringBuilder();
        foreach (ThemeSymbolsDto dto in data) {
            
            ImmutableArray<IPropertySymbol> themeProperties = GetIThemeProperties(compilation, dto.Symbol);
            
            builder.AppendAutoGenerated()
                .AppendUsings("System.Collections.Frozen")
                .AppendNamespace(dto.NameSpace)
                .AppendLine()
                .AppendLine($"{dto.Accessibility} partial class {dto.ClassName} {{")
                .AppendLine("#region RgbValues")
                .Indent(
                    static (b, args) => ThemeSymbolsDto.WriteRgbValues(b, args.themeProperties),
                    (dto, themeProperties)
                )
                .AppendLine("#endregion")
                .AppendLine()
                .AppendLine("#region AsCssVariables")
                .Indent(
                    static (b, args) => ThemeSymbolsDto.WriteAsCssVariables(b, args.themeProperties),
                    (dto, themeProperties)
                )
                .AppendLine("#endregion")
                .AppendLine("}"); 
            
            context.AddSource($"{dto.ClassName}.g.cs", builder.ToStringAndClear());
        }
    }

    private static ImmutableArray<IPropertySymbol> GetIThemeProperties(Compilation compilation, INamedTypeSymbol dtoSymbol) {
        if (IThemeProperties is null) {
            INamedTypeSymbol? iThemeSymbol = compilation.GetTypeByMetadataName(IThemeInterfaceFullName);
            if (iThemeSymbol is null) return ImmutableArray<IPropertySymbol>.Empty;

            IThemeProperties = iThemeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(symbol => symbol.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == IncludeAsCssVariableAttributeFullName))
                .ToImmutableArray();
        }
        
        IEnumerable<IPropertySymbol> currentSymbolProperties = dtoSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(symbol => symbol.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == IncludeAsCssVariableAttributeFullName));
        
        return IThemeProperties.Concat(currentSymbolProperties)
            .ToImmutableArray();
    }

}
