// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.GeneratorTools;
using Microsoft.CodeAnalysis;
using System;
using System.Buffers;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace InfiniLore.InfiniBlazor.Theming.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public static class ThemeSymbolsDtoWriter {
    private static string ToCssVariable(ReadOnlySpan<char> input) {
        int[] tempArray = ArrayPool<int>.Shared.Rent(input.Length);
        char[] result = ArrayPool<char>.Shared.Rent(input.Length + input.Length + 1); 
    
        try {
            int index = 0;
            int count = 0;

            for (int i = 1; i < input.Length; i++) {
                bool currentIsDigit = char.IsDigit(input[i]);
                bool previousIsDigit = char.IsDigit(input[i - 1]);
            
                if (!(char.IsUpper(input[i]) || currentIsDigit && !previousIsDigit)) continue;

                tempArray[count * 2] = index;
                tempArray[count * 2 + 1] = i - index;
                count++;
                index = i;
            }

            if (index < input.Length) {
                tempArray[count * 2] = index;
                tempArray[count * 2 + 1] = input.Length - index;
                count++;
            }

            result[0] = '-';// First '-'
            result[1] = '-';// Second '-'
            int writePos = 2;// Start after '--'

            for (int i = 0; i < count; i++) {
                if (i > 0)
                    result[writePos++] = '-';

                int start = tempArray[i * 2];
                int length = tempArray[i * 2 + 1];

                for (int j = 0; j < length; j++) {
                    result[writePos++] = char.ToLower(input[start + j]);
                }
            }

            return new string(result, 0, writePos);
        }
        finally {
            ArrayPool<int>.Shared.Return(tempArray);
            ArrayPool<char>.Shared.Return(result);
        }
    }
    
    public static void WritePartialClass(ThemeSymbolsDto dto, GeneratorStringBuilder builder, Compilation compilation) {
        ImmutableArray<IPropertySymbol> themeProperties = dto.GetProperties(compilation);
            
        builder.AppendAutoGenerated()
            .AppendUsings("System.Collections.Frozen")
            .AppendNamespace(dto.NameSpace)
            .AppendLine()
            .AppendLine($"{dto.Accessibility} partial {dto.TypeKeyword} {dto.ClassName} {{")
            .Indent(
                static (b, args) => {
                    b.AppendLine("#region RgbValues");
                    
                    IEnumerable<IPropertySymbol> rgbProperties = args.themeProperties
                        .Where(property => property.HasAttributeWithDisplayName(TypeNames.InterpretAsRgbAttribute));

                    b.ForEachAppendLine(rgbProperties, symbol => {
                        string propertyName = symbol.Name.Substring(0, symbol.Name.Length - 3);
                        string converterCall = $"StringColorExtensions.ConvertToRgbValues({propertyName})";
                        return $"public string {symbol.Name} => {converterCall};";
                    });
                    
                    b.AppendLine("#endregion");
                },
                (dto, themeProperties)
            )
            .AppendLine()
            .Indent(
                static (b, args) => {
                    b.AppendLine("#region AsCssVariables");
                    
                    b.AppendLine("public IEnumerable<(string, string)> AsCssVariables() {");

                    // ReSharper disable once HeapView.CanAvoidClosure
                    b.ForEachAppendLineIndented(args.themeProperties, symbol => {
                        string cssVariableName = !args.dto.GenerateVariableStorage 
                            ? ToCssVariable(symbol.Name.AsSpan()).ToQuotedString()
                            : $"{args.dto.ClassName}VariableNames.{symbol.Name}";
                            
                        string property = symbol.Name;
                            
                        return $"yield return({cssVariableName}, {property});";
                    });

                    b.AppendLine("}");
                    
                    b.AppendLine("#endregion");
                },
                (dto, themeProperties)
            )
            .AppendLine("}"); 
    }

    public static void WriteVariableNames(ThemeSymbolsDto dto, GeneratorStringBuilder builder, Compilation compilation) {
        ImmutableArray<IPropertySymbol> themeProperties = dto.GetProperties(compilation);
        
        builder.AppendAutoGenerated()
            .AppendUsings("System.Collections.Frozen")
            .AppendNamespace(dto.NameSpace)
            .AppendLine()
            .AppendLine($"public static class {dto.ClassName}VariableNames {{");

        builder.ForEachAppendLineIndented(themeProperties, symbol => {
            string cssVariableName = ToCssVariable(symbol.Name.AsSpan());
            return $"public const string {symbol.Name} = {cssVariableName.ToQuotedString()};";
        });
        
        builder.Append("}");
    }
}
