// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using CodeOfChaos.GeneratorTools;
using System.Collections.Generic;

namespace InfiniLore.InfiniBlazor.Theming.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[Generator(LanguageNames.CSharp)]
public class ThemeSymbolsGenerator : IIncrementalGenerator {
    private const string GenerateThemeSymbolsAttributeFullName = "InfiniLore.InfiniBlazor.Theming.GenerateThemeSymbols";
    private const string IncludeAsCssVariableAttributeFullName = "InfiniLore.InfiniBlazor.Theming.IncludeAsCssVariable";
    private const string IThemeInterfaceFullName = "InfiniLore.InfiniBlazor.Theming.ITheme";

    private static ImmutableArray<IPropertySymbol>? IThemeProperties { get; set; }

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValueProvider<ImmutableArray<ThemeSymbolsDto>> data = context.SyntaxProvider
            .CreateSyntaxProvider(Predicate, Transform)
            .Where(dto => dto is not null)
            .Collect()!;

        context.RegisterSourceOutput(context.CompilationProvider.Combine(data), GenerateSources);
    }

    private static bool Predicate(SyntaxNode node, CancellationToken ct) {
        return node switch {
            ClassDeclarationSyntax classDeclaration => classDeclaration.AttributeLists.Count > 0,
            RecordDeclarationSyntax recordDeclaration => recordDeclaration.AttributeLists.Count > 0,
            _ => false
        };

    }

    private static ThemeSymbolsDto? Transform(GeneratorSyntaxContext context, CancellationToken ct) {
        SemanticModel semanticModel = context.SemanticModel;

        INamedTypeSymbol? symbol = context.Node switch {
            ClassDeclarationSyntax classDeclaration => semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol,
            RecordDeclarationSyntax recordDeclaration => semanticModel.GetDeclaredSymbol(recordDeclaration) as INamedTypeSymbol,
            _ => null
        };
        if (symbol is null) return null;

        // Check if it has the GenerateThemeSymbols attribute
        bool hasGenerateThemeSymbolsAttribute = symbol.GetAttributes()
            .Any(static attr => attr.AttributeClass?.ToDisplayString() == GenerateThemeSymbolsAttributeFullName);
        if (!hasGenerateThemeSymbolsAttribute) return null;

        // Check if it implements ITheme
        bool implementsITheme = symbol.AllInterfaces
            .Any(static i => i.ToDisplayString() == IThemeInterfaceFullName);

        return implementsITheme
            ? new ThemeSymbolsDto(symbol)
            : null;
    }

    private static void GenerateSources(SourceProductionContext context, (Compilation Compilation, ImmutableArray<ThemeSymbolsDto> Data) tuple) {
        (Compilation compilation, ImmutableArray<ThemeSymbolsDto> data) = tuple;
        
        var builder = new GeneratorStringBuilder();
        foreach (ThemeSymbolsDto dto in data) {
            ImmutableArray<IPropertySymbol> themeProperties = GetProperties(compilation, dto.Symbol);
            
            builder.AppendAutoGenerated()
                .AppendUsings("System.Collections.Frozen")
                .AppendNamespace(dto.NameSpace)
                .AppendLine()
                .AppendLine($"{dto.Accessibility} partial {dto.TypeKeyword} {dto.ClassName} {{")
                .Indent(
                    static (b, args) => {
                        b.AppendLine("#region RgbValues");
                        ThemeSymbolsDto.WriteRgbValues(b, args.themeProperties);
                        b.AppendLine("#endregion");
                    },
                    (dto, themeProperties)
                )
                .AppendLine()
                .Indent(
                    static (b, args) => {
                        b.AppendLine("#region AsCssVariables");
                        ThemeSymbolsDto.WriteAsCssVariables(b, args.themeProperties);
                        b.AppendLine("#endregion");
                    },
                    (dto, themeProperties)
                )
                .AppendLine("}"); 
            
            context.AddSource($"{dto.ClassName}.g.cs", builder.ToStringAndClear());
        }
    }

    private static ImmutableArray<IPropertySymbol> GetProperties(Compilation compilation, INamedTypeSymbol dtoSymbol) {
        if (IThemeProperties is null) {
            INamedTypeSymbol? iThemeSymbol = compilation.GetTypeByMetadataName(IThemeInterfaceFullName);
            if (iThemeSymbol is null) return ImmutableArray<IPropertySymbol>.Empty;

            IThemeProperties = iThemeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(symbol => symbol.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == IncludeAsCssVariableAttributeFullName))
                .ToImmutableArray();
        }
        
        IEnumerable<IPropertySymbol> currentSymbolProperties = dtoSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(symbol => symbol.GetAttributes().Any(static attr => attr.AttributeClass?.ToDisplayString() == IncludeAsCssVariableAttributeFullName));
        
        return IThemeProperties.Concat(currentSymbolProperties)
            .ToImmutableArray();
    }

}
