name: Pull Request Check

on:
    pull_request:
        branches: [ core ]  # or 'master' depending on your default branch name

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '9.x'

            - name: Restore dependencies
              run: dotnet restore InfiniLore.InfiniBlazor.sln

            - name: Build
              run: dotnet build InfiniLore.InfiniBlazor.sln --configuration Release --no-restore
            
            - name: Run tests
              run: dotnet test InfiniLore.InfiniBlazor.sln --configuration Release --no-restore --no-build
